name: Flutter CI Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
        
    - name: Build Flutter App
      run: |
        flutter create --org com.bodadroid noor_app
        cp -r lib noor_app/
        cp pubspec.yaml noor_app/
        cd noor_app
        flutter build apk --release
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: Noor-App-Flutter-Release
        path: noor_app/build/app/outputs/flutter-apk/app-release.apk
